# Generated by Django 4.0.3 on 2022-04-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=5)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('flight_type', models.CharField(choices=[('OW', 'One Way'), ('RT', 'Round Trip')], max_length=2)),
                ('flight_class', models.CharField(choices=[('FC', 'First Class'), ('BC', 'Business Class'), ('E', 'Economy')], max_length=2)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flights', to='flight.airplane')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arriving_flights', to='flight.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='moving_flights', to='flight.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=20)),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images')),
                ('tickets', models.ManyToManyField(blank=True, to='flight.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flight.city'),
        ),
    ]
