# Generated by Django 4.0.3 on 2022-05-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flight.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight', '0002_rename_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flight.flight'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(default=flight.models.rand_code, max_length=20, unique=True),
        ),
    ]
