# Generated by Django 4.0.3 on 2022-05-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_remove_profile_tickets_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='arriving_flights', to='flight.city'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='moving_flights', to='flight.city'),
        ),
    ]
